 CREATE TABLE  "TEACHERS" 
   (		"ID" NUMBER(2,0) NOT NULL PRIMARY KEY, 
		"NAME" VARCHAR2(14) ,
		"SUBJECT" VARCHAR2(14),
		"BOSS_ID" NUMBER(2,0)
   );

CREATE TABLE  "GROUPS" 
   (		"GROUPNUM" NUMBER(5,0) NOT NULL PRIMARY KEY, 
		"CHIEFID" NUMBER(2,0),
		"PROFESSION" VARCHAR2(14),
                 FOREIGN KEY ("CHIEFID") REFERENCES  "TEACHERS" ("ID")
   ) ;

CREATE TABLE  "STUDENTS" 
   (		"ID" NUMBER(2,0) NOT NULL, 
		"NAME" VARCHAR2(14), 
		"BIRHTDAY" DATE,
		"GROUP" NUMBER(5,0),
		"SAL" NUMBER(5,0),
		PRIMARY KEY ("ID"),
		 FOREIGN KEY ("GROUP") REFERENCES  "GROUPS" ("GROUPNUM")
   ) ;

CREATE SEQUENCE  TEACH_ID
	INCREMENT BY 1
	START WITH 1
	MAXVALUE 51
	CACHE 50 


INSERT INTO TEACHERS VALUES(TEACH_ID.NEXTVAL,'Prof.'||TEACH_ID.CURRVAL,
			'subject'||TEACH_ID.CURRVAL, NULL);

DECLARE
	NEWname TEACHERS.NAME%TYPE;
	NEWsubject TEACHERS.SUBJECT%TYPE;
	NEWNODECOUNT NUMBER(7); 
BEGIN
	NEWNODECOUNT := 9;
        NEWname := 'Prof.';
	NEWsubject := 'subject';
         
	for i in 2..NEWNODECOUNT
	loop
		INSERT INTO TEACHERS VALUES(TEACH_ID.NEXTVAL,NEWname||TEACH_ID.CURRVAL,
			NEWsubject||TEACH_ID.CURRVAL, 1);
	end loop;
END;





CREATE SEQUENCE  GROUP_NUM
	INCREMENT BY 1
	START WITH 1111
	MAXVALUE 2222
	CACHE 50 ;

DECLARE
	NEWGroupNum GROUPS.GROUPNUM%TYPE;
	NEWPROFESSION GROUPS.PROFESSION%TYPE;
	NEWCHIEFID GROUPS.CHIEFID%TYPE;
	
	NEWNODECOUNT NUMBER(7); 
BEGIN
	NEWNODECOUNT := 5;
        NEWPROFESSION := 'PROFESSION';
         
	for i in 1..NEWNODECOUNT
	loop
		INSERT INTO GROUPS VALUES(GROUP_NUM.NEXTVAL, i,
			NEWprofession||i );
	end loop;
END;

INSERT INTO GROUPS VALUES(GROUP_NUM.NEXTVAL, 2,
			'PROFESSION'||'2' );
INSERT INTO GROUPS VALUES(GROUP_NUM.NEXTVAL, 4,
			'PROFESSION'||'4');

CREATE SEQUENCE  STUD_ID
	INCREMENT BY 1
	START WITH 1
	MAXVALUE 51
	CACHE 50 

DECLARE
	NEWname STUDENTS.NAME%TYPE;
	NEWBIRHTDAY DATE;
	NEWGROUPNUM NUMBER(5,0);
	NEWNODECOUNT NUMBER(7); 
BEGIN
	NEWNODECOUNT := 28;
        NEWname := 'name';
         
	for i in 1..7
	loop
		FOR j in 1..4
		loop
		 INSERT INTO STUDENTS VALUES(STUD_ID.NEXTVAL,'name'||stud_ID.CURRVAL, '04/05/95', 1110+i, 100*j);
		end loop;
	end loop;
END;
	
INSERT INTO TEACHERS VALUES(TEACH_ID.NEXTVAL,'Prof.'||TEACH_ID.CURRVAL,
			'subject'||TEACH_ID.CURRVAL );


CREATE SEQUENCE  GROUP_NUM
	INCREMENT BY 1
	START WITH 1111
	MAXVALUE 2222
	CACHE 50 ;

DECLARE
	NEWGroupNum GROUPS.GROUPNUM%TYPE;
	NEWPROFESSION GROUPS.PROFESSION%TYPE;
	NEWCHIEFID GROUPS.CHIEFID%TYPE;
	
	NEWNODECOUNT NUMBER(7); 
BEGIN
	NEWNODECOUNT := 5;
        NEWPROFESSION := 'PROFESSION';
         
	for i in 1..NEWNODECOUNT
	loop
		INSERT INTO GROUPS VALUES(GROUP_NUM.NEXTVAL, i,
			NEWprofession||i );
	end loop;
END;

INSERT INTO GROUPS VALUES(GROUP_NUM.NEXTVAL, 2,
			'PROFESSION'||'2' );
INSERT INTO GROUPS VALUES(GROUP_NUM.NEXTVAL, 4,
			'PROFESSION'||'4');

CREATE SEQUENCE  STUD_ID
	INCREMENT BY 1
	START WITH 1
	MAXVALUE 51
	CACHE 50 

DECLARE
	NEWname STUDENTS.NAME%TYPE;
	NEWBIRHTDAY STUDENTS.BIRHTDAY%TYPE;
	NEWGROUPNUM STUDENTS.GROUP%TYPE;
	NEWNODECOUNT NUMBER(7); 
BEGIN
	NEWNODECOUNT := 28;
        NEWname := 'name';
         
	for i in 1..7
	loop
		FOR j in 1..4
		loop
		 INSERT INTO "Students" VALUES(STUD_ID.NEXTVAL,'name'||stud_ID.CURRVAL, '04/05/95', 1110+i, 100*j);
		end loop;
	end loop;
END;
	


